### ISSUE TITLE
Description of enriched-zircon

### ISSUE THREAD

**Issue by sakuro** [brevven/zirconium#1]
Which is intended?

Tech : ammonia
https://github.com/brevven/zirconium/blob/00e15527d4f956bcc6c7cf48b0f11c2af51f76e0/locale/en/zirconium.cfg#L33

Recipe: sulfuric acid
https://github.com/brevven/zirconium/blob/00e15527d4f956bcc6c7cf48b0f11c2af51f76e0/locale/en/zirconium.cfg#L46

Current implementation seems using sulfuric acid
https://github.com/brevven/zirconium/blob/00e15527d4f956bcc6c7cf48b0f11c2af51f76e0/zirconium-enriched.lua#L34

**Comment by brevven** [comment]
Thanks! It is supposed to be sulfuric acid. I'll fix it in the `en` locale.
