### ISSUE TITLE
recipe-name.zirconia is missing from locale/en

### ISSUE THREAD

**Issue by sakuro** [brevven/zirconium#3]
Factorio 1.1.35 + Zirconium 0.0.7 (+ Krastorio 2 1.1.3 and some other mods :-)

![image](https://user-images.githubusercontent.com/10973/122411401-b1957f80-cfbf-11eb-8275-0f0ac5e9b62d.png)

**Comment by brevven** [comment]
Thanks. Should be fixed in an upcoming release!
